spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.121.36.206/sti?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    hibernate:
#      엔티티 바꾸거나 추가하면 아래 옵션 update로 바꿔서 디버그 시켰다가 원상태로
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        storage_dialect: innodb
        format_sql: true
    database: mysql
    defer-datasource-initialization: true
  data:
    redis:
      port: 6379
      host: localhost
server:
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    com.example.seoultechInvestment.controller: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug
    #각 패키지에 디폴트 로깅 레벨을 지정할 수 있다.